# Generated by Django 4.2.15 on 2024-08-28 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vege", "0005_recipe_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="recipe_view_count",
            field=models.IntegerField(default=1),
        ),
    ]
